### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by Newbytee** [Harmon758/mb_DiscordRichPresence#5]
It likes to throw this error onto me when I try adding the ZIP file using MusicBee's add plugin-thingy.

I'm using the Windows Store version of MusicBee, by the way.

![image](https://user-images.githubusercontent.com/4428753/35352915-cc022518-0145-11e8-91ec-29eb38b1b65b.png)

**Comment by MichaelGatesDev** [comment]
As far as I understand, the Windows Store version of MusicBee is almost exactly the same as the standard version.

Could you post your `error.dat` file located here: `"%AppData%\Roaming\MusicBee\ErrorLog.dat"` ?

**Comment by Harmon758** [comment]
@Newbie13XD DM'ed me on Discord and I helped them to debug the issue.

I tested the plugin on various platforms and confirmed that it works on Windows 10, for both the Windows Store version as well as the installer version, downloaded through MusicBee's site.

The problem ended up being that @Newbie13XD manually unzipped the plugin and added both DLL files individually as plugins through the MusicBee interface. This resulted in errors, but they were still added to the plugins folder. After realizing their mistake, they tried to add the plugin by selecting the ZIP file/folder in the interface, but it errored due to the already existing DLL files. The solution was to delete those from the plugins folder and re-add the ZIP.

Throughout this process, I found out that the MusicBee error log and other app/cached data for the Windows Store version isn't in `%AppData%\MusicBee`, but rather something like `%LocalAppData%\Packages\xxxxxx.MusicBee_9999999\LocalCache\Roaming\MusicBee`, per https://getmusicbee.com/forum/index.php?topic=23833.0, and that when trying to access the error log through Help -> Support -> View Error Log, it errors, saying the system cannot find the path specified.

Another thing I found out, while debugging this issue, is that Visual C++ Redistributable for Visual Studio 2017 is a binary-compatible in-place upgrade for the 2015 Redistributable and shares the same registry keys, per https://developercommunity.visualstudio.com/content/problem/14701/visual-c-redistributable-for-visual-studio-2015-ca.html. Because of this, installing the 2017 Redistributable removes the 2015 Redistributable from being shown as installed, and it's not possible to install the 2015 Redistributable when the 2017 Redistributable is already installed. As such, I've updated the requirements in the README with 9a69e756b69e4ea42205d96283dbe09892c91f8d.

Also, although the [Discord Rich Presence documentation](https://discordapp.com/developers/docs/rich-presence/how-to#step-0-get-the-sdk) states that the "precompiled libraries depend on the Visual C++ Redistributable for Visual Studio 2015", the [Discord RPC repository's README](https://github.com/discordapp/discord-rpc#from-repo) says that there's a flag to "enable to statically link the CRT, avoiding requiring users install the redistributable package" and that "the prebuilt binaries enable this option". Since the plugin uses the prebuilt binaries, the Redistributable might not even be a necessary requirement. However, I haven't tested this yet, so I'll leave it in the README for now.
